#!/bin/sh
## Functions for porteus init
## Author brokenman, modified for Debiandog by fredx181
# 2024-03-18 fredx181 modified for pseudo-full install

# Modified by gumanzoy https://github.com/PocketHandyBox

# Export some color functions
RED=`echo -e '\e[1;31m'`
GREEN=`echo -e '\e[1;32m'`
YELLOW=`echo -e '\e[1;33m'`
BLUE=`echo -e '\e[1;34m'`
PURPLE=`echo -e '\e[1;35m'`
CYAN=`echo -e '\e[1;36m'`
BOLD=`echo -e '\e[1m'`
RST=`echo -e '\e[0m'` # Reset Color
i="${YELLOW}^ ${RST}"
m="${YELLOW}->${RST}"

param() {
egrep -qo "(^| )$1( |\$)" /proc/cmdline
}

value() {
egrep -o "(^| )$1=[^ ]+" /proc/cmdline | cut -d= -f2 | tail -n1
}

multivalue() {
val=""
val=`egrep -o "(^| )$1=[^ ]+" /proc/cmdline | cut -d= -f2` && echo $val | sed 's/ /,/g'
}

debug() {
[ $DBUG ] || return 0
echo -e "\n: Debugging started. Here is the shell for you. Type your desired commands."
echo -en ": Hit Ctrl+D to continue booting or press Ctrl+Alt+Del to reboot."
sh
}

# Load network kernel modules for PXE boot
load_net_modules() {
#softdep for r8169 https://bugzilla.kernel.org/show_bug.cgi?id=204343
lspci | grep 0200: >/tmp/lspci
grep -q 10ec: /tmp/lspci && modprobe -q realtek
grep -q 14e4: /tmp/lspci && modprobe -q broadcom
for x in `cut -d: -f3-4 /tmp/lspci | sed s/:/.*/g | tr a-z A-Z`; do
	mod=`grep $x /lib/modules/$(uname -r)/modules.alias | tail -n1 | rev | cut -d" " -f1 | rev`
	modprobe -q $mod
done
ls /sys/class/net | grep -q eth && return 0
for x in `find /lib/modules/$(uname -r)/kernel/drivers/net/ethernet -name "*.ko" | sed 's/.ko//g'`
	do mod=`basename $x`
	modprobe -q $mod
	ls /sys/class/net | grep -q eth && break || rmmod $mod 2>/dev/null
done
}

# Run fstab for setup
fstab() {
rm -f /tmp/devices
param nocd || for x in /dev/sr*; do blkid $x >>/tmp/devices; done
param nohd || blkid | egrep -v '/dev/sr|/dev/loop|/dev/mapper' >>/tmp/devices
dev=`egrep -v 'TYPE="sw|TYPE="LVM|TYPE=".*_raid_member"' /tmp/devices 2>/dev/null | cut -d: -f1 | cut -d/ -f3 | sort | uniq`
for x in $dev; do
[ -d /mnt/$x ] && continue
fs=`grep -w /dev/$x /tmp/devices | egrep -o ' TYPE=[^ ]+' | cut -d'"' -f2`
if [ $fs = vfat ]; then
	echo "/dev/$x /mnt/$x vfat $MOPT,umask=0,check=s,utf8 0 0" >> /etc/fstab
elif [ $fs = ntfs ] && grep -q ntfs3 /proc/filesystems ; then
	echo "/dev/$x /mnt/$x ntfs3 $MOPT,force,sparse 0 0" >> /etc/fstab
elif [ $fs = ntfs ]; then
	echo "/dev/$x /mnt/$x ntfs $MOPT,umask=0,nls=utf8 0 0" >> /etc/fstab
else
	echo "/dev/$x /mnt/$x $fs $MOPT 0 0" >> /etc/fstab
fi
mkdir /mnt/$x
mount /mnt/$x 2>/dev/null && continue
modprobe -q $fs && mount /mnt/$x 2>/dev/null && continue
sed -i "/$x /d" /etc/fstab
rmdir /mnt/$x
done
}

#enable_swap() {
#if [ -z "`egrep -o " noswap( |\$)" /proc/cmdline`" -a -e /tmp/devices ]; then
#	#echo -e "\n# Swap partitions:" >>/etc/fstab
#	echo -n "Loading swap partition..."
#	for x in `grep 'TYPE="swap"' /tmp/devices | cut -d: -f1`; do echo "$x none swap sw,pri=1 0 0" >>/etc/fstab; done
#fi
#}

# Mount things
mount_device() {
fs=`blkid /dev/$1 | egrep -o ' TYPE=[^ ]+' | cut -d'"' -f2`
[ "$fs" ] || return 0
mkdir /mnt/$1
if [ $fs = vfat ]; then
	mount /dev/$1 /mnt/$1 -o $MOPT,umask=0,check=s,utf8 2>/dev/null || rmdir /mnt/$1
elif [ $fs = ntfs ] && grep -q ntfs3 /proc/filesystems ; then
	mount /dev/$1 /mnt/$1 -t ntfs3 -o $MOPT,force,sparse 2>/dev/null || rmdir /mnt/$1
elif [ $fs = ntfs ]; then
	mount /dev/$1 /mnt/$1 -o $MOPT,umask=0,nls=utf8 2>/dev/null || rmdir /mnt/$1
#	ntfs-3g /dev/$1 /mnt/$1 -o $MOPT 2>/dev/null || rmdir /mnt/$1
else
	mount /dev/$1 /mnt/$1 -o $MOPT 2>/dev/null && return 0
	modprobe -q $fs && mount /dev/$1 /mnt/$1 -o $MOPT || rmdir /mnt/$1
fi
}

# Search for file/folder path
search() { FND=none; for x in `ls /mnt | tac`; do
[ $1 /mnt/$x/"$2" ] && { DEV=$x; FND=y; break; }; done
[ $FND = y ]; }

# Delay booting a little until devices have settled
nap() { echo -en "${i}device not ready yet? delaying ${YELLOW}${SLEEP}${RST} seconds \r"; sleep 1; }
lazy() { SLEEP=6; while [ $SLEEP -gt 0 -a $FND = none ]; do nap; let SLEEP=SLEEP-1; fstab; search $1 "$2"; done }

# Search for file/folder path /mnt/ or /dev/ or UUID/LABEL
locate() { LPATH="`echo $2 | cut -b-5 | sed s@/dev@/mnt@`"
if [ "$LPATH" = /mnt/ ]; then
    DEV="`echo $2 | cut -d/ -f3`"; LPTH="`echo $2 | cut -d/ -f4-`"
    [ $1 /mnt/$DEV/"$LPTH" ] && return 0
    SLEEP=6
    while [ $SLEEP -gt 0 -a ! -b /dev/$DEV ]; do nap; let SLEEP=SLEEP-1; fstab; done
    [ -d /mnt/$DEV ] || mount_device $DEV
    [ $1 /mnt/$DEV/"$LPTH" ]
elif [ "$LPATH" = UUID: -o "$LPATH" = LABEL ]; then
    ID="`echo $2 | cut -d: -f2 | cut -d/ -f1`"; LPTH="`echo $2 | cut -d/ -f2-`"; DEV="`blkid | grep $ID | cut -d: -f1 | cut -d/ -f3`"; SLEEP=6
    while [ $SLEEP -gt 0 -a "$DEV" = "" ]; do nap; let SLEEP=SLEEP-1; fstab; DEV="`blkid | grep $ID | cut -d: -f1 | cut -d/ -f3`"; done
    [ -d /mnt/$DEV ] || mount_device $DEV
    [ $1 /mnt/$DEV/"$LPTH" ]
else
    LPTH="$2"; search $1 "$2" || lazy $1 "$2"
fi }

# Search for live folder
locate_data() {
ISO="`egrep -io '(^| )from=.*\.iso( |\$)' /proc/cmdline | cut -d= -f2 | sed 's/[ ]$//'`"
if [ -n "$ISO" ]; then
    locate -e "$ISO"
    if [ $? -ne 0 ]; then echo "${i}couldn't find ISO file${CYAN} $ISO ${RST}"
    else
        mkdir /mnt/isoloop && mount -o loop /mnt/$DEV/"$LPTH" /mnt/isoloop
        if [ $? -ne 0 ]; then rmdir /mnt/isoloop
            echo "${i}Cannot mount ISO${CYAN} /mnt/$DEV/$LPTH ${RST}"
        elif [ -d /mnt/isoloop/$FOLDER ]; then
            DATADEV=/mnt/isoloop; BOOTDEV=/mnt/$DEV
            ISOSRC="`echo /mnt/$DEV/$LPTH | tr -s /`"
            echo "${i}ISO=$ISO"
            return 0
        fi
    fi
    echo "${i}Cannot boot from ISO file. Press 'enter' to search through all devices"
    read -s
fi
if [ $IP ]; then
    mkdir -p /mnt/nfs
    modprobe -q nfsv4; mount -t nfs4 $IP:$NFSPATH /mnt/nfs -o ro,nolock 2>/dev/null || { modprobe -q nfsv3; mount -t nfs $IP:$NFSPATH /mnt/nfs -o ro,nolock 2>/dev/null; }
    [ $? -ne 0 ] && echo "${i}Cannot mount NFS${CYAN} $IP:$NFSPATH ${RST}"
    if [ $FROM ]; then
        FOLDER=$FROM/$FOLDER
        CMDIR=$FROM/$CMDIR
    fi
    DATADEV=/mnt/nfs
    if [ -d $DATADEV/$FOLDER ]; then
        BOOTDEV=network
        echo "${i}mount NFS${BOLD} $IP:$NFSPATH ${RST}"
        return 0
    fi
    echo "${i}Cannot find${BOLD} $IP:$NFSPATH/$FOLDER ${RST}"
    echo "${YELLOW}Press 'enter' to search through all devices${RST}"
    read -s
elif [ $FROM ]; then
    locate -d $FROM/$FOLDER
    if [ $? -ne 0 ]; then
        echo "${i}couldn't find${BOLD} $FROM/$FOLDER ${RST}Correct your from= cheatcode"
        echo "${YELLOW}Press 'enter' to search through all devices${RST}"
        read -s
    else
        DIR=`echo /$LPTH | rev | cut -d/ -f2- | rev | tr -s /`
        [ $DIR ] && FOLDER=$DIR/$FOLDER
        [ $DIR ] && CMDIR=$DIR/$CMDIR
        DATADEV=/mnt/$DEV
        return 0
    fi
fi
search -d $FOLDER || lazy -d $FOLDER
[ $? -eq 0 ] || fatal
DATADEV=/mnt/$DEV
}

# Failed to initiate changes. Creating temporary changes on tmpfs for this session.
fail_chn() {
mount -t tmpfs -o size=$RAMSIZE tmpfs /memory/changes
CHANGES=memory; CHNDEV=memory; CHNEXIT=""; PFULL=""
touch /etc/nochanges
}

fail_chn_msge() {
[ "$PFULL" ] && echo "${i}Failed to setting up${BOLD} pfull= ${RST}filesystem"
echo "${YELLOW}Press 'enter' to continue booting, using memory only${RST}"
read -s
if [ "$PFULL" ]; then [ -f "$DATADIR"/01-filesystem.squashfs ] || fatal; fi
fail_chn
}

clean_changes_dir() {
local U=/memory/changes
[ -n "$1" ] && local U="$1"
if [ -z "$PFULL" ] && [ -f $U/clear-changes-on-reboot ]; then
	echo "${i}${CYAN}changes content signalled to be cleared${RST}"
	rm -rf $U/* 2>/dev/null && return 0
fi
rm -rf $U/$UDIR/dev/* $U/$UDIR/proc/* $U/$UDIR/run/* $U/$UDIR/sys/* $U/$UDIR/tmp/* 2>/dev/null
rm -rf $U/upperdir/media $U/upperdir/mnt $U/upperdir/var/tmp 2>/dev/null
}

# Mount module
mount_module() {
# NUM+1 if /memory/images/$NAME exists already
if [ -d /memory/images/"$NAME" ]; then let NUM=NUM+1
	NAME="${NAME}-${NUM}"
fi
mkdir -p /memory/images/"$NAME"
mount -o loop "$MODULE" /memory/images/"$NAME" 2>/dev/null
if [ $? -eq 0 ]; then
	echo -n " ${m} "; basename "$MODULE"
	[ "$NAME" != "01-filesystem.squashfs" ] && echo "/memory/images/$NAME" >>/tmp/lowerdir
else
	echo "${i}${CYAN}Cannot read $NAME - corrupted module?${RST}"
	rmdir /memory/images/"$NAME"
fi
}

# testing filesystem on changes for posix compatibility
posix_test() {
local T1=/mnt/$DEV/"$LPTH"/._test1
local T2=/mnt/$DEV/"$LPTH"/._test2
touch "$T1" && ln -s "$T1" "$T2" 2>/dev/null && chmod +x "$T1" 2>/dev/null && [ -x "$T1" ] && chmod -x "$T1" 2>/dev/null && [ ! -x "$T1" ] && rm -f "$T1" "$T2" 2>/dev/null && return 0
echo "${i}filesystem /mnt/$DEV/$LPTH is posix compatible"
rm -f "$T1" "$T2" 2>/dev/null
return 1
}

pos_fail() {
echo "${i}A Windows filesystem (FAT, NTFS) or other non-posix compatible filesystem
has been detected on changes${BOLD} /mnt/$DEV/$LPTH ${RST}.
Your changes cannot be saved directly to the specified storage media.
Please use the ${CYAN}makepfile${RST} to create a .dat container
and use it for saving your changes after your next reboot."
fail_chn_msge
}

# mount changes or pfull directory
mount_changes_bind() {
CHNDIR=changes
[ "$PFULL" ] && CHNDIR=pfull
if param changes-ro || [ "$CHNEXIT" ]; then
	mkdir -p /memory/images/changes-exit
	mount -o bind /mnt/$DEV/"$LPTH"/$CHNDIR /memory/images/changes-exit 2>/dev/null
else
	mount -o bind /mnt/$DEV/"$LPTH"/$CHNDIR /memory/changes 2>/dev/null
fi
if [ "$CHNEXIT" = +EXIT ]; then
	echo "${i}${CYAN}option +EXIT is being used, changes are NOT written in memory${RST}"
	echo "${i}${CYAN}temporary changes will be in /mnt/$DEV/$LPTH/tmp-changes ${RST}"
	[ -d /mnt/$DEV/"$LPTH"/tmp-changes ] && rm -rf /mnt/$DEV/"$LPTH"/tmp-changes 2> /dev/null
	mkdir -p /mnt/$DEV/"$LPTH"/tmp-changes
	mount -o bind /mnt/$DEV/"$LPTH"/tmp-changes /memory/changes 2>/dev/null
	[ $? -eq 0 ] && touch /tmp/tmp-changes
fi
}

# mount changes file container
mount_changes_loop() {
if blkid /mnt/$DEV/"$LPTH" 2>/dev/null | egrep -o ' TYPE=[^ ]+' | grep -q _LUKS; then
	echo "${i}found LUKS encrypted .dat container - unsupported"
	fail_chn_msge
	return 1
	#for x in dm_crypt cryptd cbc sha256_generic aes_generic aes_x86_64; do modprobe $x 2>/dev/null; done
	#losetup /dev/loop2 /mnt/$DEV/$LPTH
	#echo "${i}found encrypted .dat container"
	#cryptsetup luksOpen /dev/loop2 crypt
	#mount /dev/mapper/crypt /memory/changes 2>/dev/null && touch /memory/changes/._test1 2>/dev/null
elif param changes-ro || [ "$CHNEXIT" ]; then
	mkdir -p /memory/images/changes-exit
	# mount changes file container
	mount -o loop /mnt/$DEV/"$LPTH" /memory/images/changes-exit 2>/dev/null
else
	mount -o loop /mnt/$DEV/"$LPTH" /memory/changes 2>/dev/null
fi
if [ $? -ne 0 ]; then
	[ -d /memory/images/changes-exit ] && rmdir /memory/images/changes-exit 2>/dev/null
	echo "${i}Cannot mount${BOLD} /mnt/$DEV/$LPTH ${RST}changes file container"
	fail_chn_msge
	return 1
elif [ -d /memory/images/changes-exit ]; then # container mounted, test filesystem is writable
	touch /memory/images/changes-exit/._test1 2>/dev/null
else
	touch /memory/changes/._test1 2>/dev/null
fi
if [ $? -ne 0 ]; then
	if [ -d /memory/images/changes-exit ]; then
		umount /memory/images/changes-exit 2>/dev/null && rmdir /memory/images/changes-exit 2>/dev/null
	else
		umount /memory/changes 2>/dev/null
	fi
	echo "${i}changes${BOLD} /mnt/$DEV/$LPTH ${RST}filesystem is not writable"
	fail_chn_msge
	return 1
else
	rm -f /memory/changes/._test1 /memory/images/changes-exit/._test1 2>/dev/null
	return 0
fi
}

fatal() {
echo "${BOLD}/$FOLDER/01-filesystem.squashfs not found!${RST}    
You are maybe using an unsupported boot device (eg. RAID SCSI or SAS).
${RED}Make sure UEFI Secure Boot is disabled!${RST}
Workaround: Copy the directory /$FOLDER from your boot device to internal SATA
disk, eg. to ${BOLD}/mnt/sda1/$FOLDER${RST} or ${BOLD}C:\\$FOLDER${RST}. Then try to boot again.
Make sure that your boot parameters (cheatcodes) are correct.

${BOLD}Press ${YELLOW}space/enter ${RST}${BOLD}to unmount all devices and reboot
or ${YELLOW}any other key ${RST}${BOLD}to drop to the debug shell.${RST}"
read -s -n1 ans
if [ "$ans" = "" ]; then
	umount /mnt/* 2>/dev/null
	umount -a 2>/dev/null
	reboot -f
else
echo "${CYAN}Here is debugging shell for you, unmount all partitions
and press Ctrl+Alt+Del when you finish. Good luck!${RST}"
sh
fi
}

pseudo_fatal() {
echo "Data not found for pseudo-full install ${BOLD}/mnt/$DEV/$LPTH/pfull/filesystem${RST}
${BOLD}Press ${YELLOW}space/enter ${RST}${BOLD}to unmount all devices and reboot
or ${YELLOW}any other key ${RST}${BOLD}to drop to the debug shell.${RST}"
read -s -n1 ans
if [ "$ans" = "" ]; then
	umount /mnt/* 2>/dev/null
	umount -a 2>/dev/null
	reboot -f
else
echo "${CYAN}Here is debugging shell for you, unmount all partitions
and press Ctrl+Alt+Del when you finish. Good luck!${RST}"
sh
fi
}
