#!/bin/sh
### linuxrc script by brokenman <http://www.porteus.org>
### modified for Debiandog by fredx181
# 2024-03-18 fredx181 modified for pseudo-full install

# Modified by gumanzoy https://github.com/PocketHandyBox

export PATH=/bin:/usr/bin:./

# Source functions
. ./finit

# Enable pivot_root in initramfs to let it behave like initrd:
if [ -d /m ]; then
    mount -t tmpfs -o mode=0755 tmpfs /m
    cp -a ??* /m 2>/dev/null
    exec switch_root /m linuxrc "$@"
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo 0 >/proc/sys/kernel/printk

## Check for debug
param debug && DBUG=1

clear
echo "${BOLD}Starting init script.${RST}"

# Variables:
KERNEL=`uname -r`

FOLDER=`value folder`
if [ -z "$FOLDER" ]; then FOLDER=live
CMDIR=live
#[ `uname -m` = i686 ] && FOLDER=live32
else CMDIR=$FOLDER
fi

FROM=`value from`
LANGM=`value lang`; [ "$LANGM" = en_US ] && LANGM=""

IP=`value ip | cut -d: -f2`
NFSPATH=`value nfspath`; [ $NFSPATH ] || NFSPATH=/srv/pxe
NFSRW=`value nfsrw`
MOPT=`value mopt`; [ $MOPT ] || MOPT="noatime,nodiratime,suid,dev,exec,async"
CHANGES=`value changes`
PFULL=`value pfull`; [ $PFULL ] && CHANGES=$PFULL
RAMSIZE=`value ramsize`; [ $RAMSIZE ] || RAMSIZE=60%

LOAD=`multivalue load | sed 's/[,;]/|/g'`; [ $LOAD ] || LOAD=._null
NOLOAD=`multivalue noload | sed 's/[,;]/|/g'`; [ $NOLOAD ] || NOLOAD=._null
EXTRAMOD=`multivalue extramod | sed 's/[,;]/ /g'`
RAMMOD=`multivalue rammod | sed 's/[,;]/|/g'`
ROOTCOPY=`value rootcopy`

NVIDIA=`value nvidia`
[ "$NVIDIA" = no -o "$NVIDIA" = none ] && NVIDIA=""

livedbg=/var/log/livedbg

## Let's start!
echo "${i}loading kernel modules..."

# List of mmc kernel modules. To unload them in case of unused
MODLISTMMC="cb710-mmc mmc_block sdhci-acpi sdhci-pci tifm_sd via-sdmmc vub300 wbsd "
echo "$MODLISTMMC" >> modlist

MODPBLST=`value modprobe.blacklist | sed 's/,/|/g'`

# Blacklist kernel modules
if [ -n "$MODPBLST" ]; then
    sed -E "s/($MODPBLST) //g" -i modlist
    MODPBLST=`value modprobe.blacklist | sed 's/,/ /g;s/[_-]/?/g'`
    for MODULE in $MODPBLST; do
    find /lib/modules/$KERNEL/kernel/ -name "$MODULE"'.*' -delete 2>/dev/null
    done
fi

if param nocd || [ $IP ]; then
sed 's/pata_[0-9a-z]\{3,\} //g' -i modlist
fi

# Load kernel modules
modprobe -qa `cat modlist`

mount -t devtmpfs none /dev

# Load network kernel modules in case of PXE boot
if [ $IP ] || [ $NFSRW ]; then
    load_net_modules
    udhcpc
fi

if [ $NFSRW ]; then
    mkdir -p /mnt/nfsrw
    modprobe -q nfsv4; mount -t nfs4 $NFSRW /mnt/nfsrw -o rw,nolock 2>/dev/null || { modprobe -q nfsv3; mount -t nfs $NFSRW /mnt/nfsrw -o rw,nolock 2>/dev/null; }
    if [ $? -eq 0 ]; then
        echo "${i}mount nfsrw=$NFSRW /mnt/nfsrw"
    else rmdir /mnt/nfsrw 2>/dev/null
        echo "${i}Cannot mount ${BOLD}nfsrw=$NFSRW ${RST}"
    fi
fi

param noauto && MOUNT=noauto
if param noauto && [ -z "$CHANGES" ]; then
    MOPT='ro,'"$MOPT"
    MOUNT=ro
fi

# Create /etc/fstab and mount devices:
fstab

#To Do
#enable_swap

debug

# Searching for live folder
echo "${i}searching for $FOLDER folder"
locate_data

# DATADEV value example /mnt/sda1
# DATADIR value example /mnt/sda1/live
DATADIR="`echo $DATADEV/$FOLDER | tr -s /`"

echo "${i}using data from $DATADIR          "
# 10 spaces at the end added to overwrite nap() message "device not ready yet? delaying X seconds"

# Create file /mnt/live/etc/homedrv for use in
# scripts 'makepfile' and 'pseudofull-setup'
echo $DATADIR > /etc/homedrv

debug

# Setup changes
CHNEXIT="`echo $CHANGES | cut -d: -f1`"
[ "$CHNEXIT" = EXIT -o "$CHNEXIT" = +EXIT ] && CHANGES="`echo $CHANGES | cut -d: -f2-`" || CHNEXIT=""

if [ -z "$CHANGES" ] || [ "$CHANGES" = memory ]; then
    echo "${i}changes cheatcode not found, using memory only"
    fail_chn
else
    [ "$PFULL" ] && echo "${i}setup pfull=$PFULL directory" || echo "${i}setting up directory for changes=$CHANGES"
    [ "$DATADEV" = /mnt/isoloop ] && CHNDEV="$BOOTDEV" || CHNDEV="$DATADEV"
    [ -r "$CHNDEV/$CHANGES" ] && { DEV="`echo $DATADEV | sed s@/mnt/@@`"; LPTH="$CHANGES"; } || locate -r "$CHANGES"
    if [ $? -ne 0 ]; then # cannot locate changes dir
        # 12 spaces at the end added to overwrite nap() message "device not ready yet? delaying X seconds"
        [ "$PFULL" ] && echo "${i}couldn't find ${BOLD}pfull=$PFULL               ${RST}" || echo "${i}couldn't find ${BOLD}changes=$CHANGES             ${RST}"
        fail_chn_msge
    elif [ -d /mnt/$DEV/"$LPTH" ] && touch /mnt/$DEV/"$LPTH"/._test1 2>/dev/null; then
        # filesystem is writable, testing for posix compatibility
        posix_test || pos_fail
    elif [ -d /mnt/$DEV/"$LPTH" ]; then
        echo "${i}changes${BOLD} /mnt/$DEV/$LPTH ${RST}filesystem is not writable"
        fail_chn_msge
    elif [ -f /mnt/$DEV/"$LPTH" ] && [ -s /mnt/$DEV/"$LPTH" ]; then
        # found changes file container
        mount_changes_loop
    fi
    if [ "$CHANGES" != memory ] && [ -d /mnt/$DEV/"$LPTH" ]; then
        if [ -z "$PFULL" ]; then mkdir -p /mnt/$DEV/"$LPTH"/changes
        else [ -d /mnt/$DEV/"$LPTH"/pfull/filesystem/usr/bin ] || pseudo_fatal
        fi
        # found changes or pfull directory
        mount_changes_bind
    fi
    [ "$CHNDEV" != memory ] && CHNDEV=/mnt/$DEV
    if [ -d /memory/images/changes-exit ]; then
        CHNEXIT=$CHNDEV/"$LPTH"; echo "$CHNEXIT" >/tmp/changes-exit
        if [ ! -f /tmp/tmp-changes ]; then
            echo "${i}${CYAN}changes will be saved only during reboot/shutdown${RST}"
            mount -t tmpfs -o size=$RAMSIZE tmpfs /memory/changes
            CHANGES=memory
        fi
    fi
fi

debug

if [ -f /memory/changes/clear-changes-on-reboot ]; then
	echo "${i}${CYAN}changes content signalled to be cleared${RST}"
	rm -rf /memory/changes/*
fi

# Disable loading 01-filesystem.squashfs for pfull= setup
[ "$PFULL" ] && NOLOAD="01-filesystem.squashfs|$NOLOAD"

# Find base modules
find $DATADIR -maxdepth 1 -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >/tmp/modules

# Find kernel modules squashfs
find $DATADIR -maxdepth 2 -name "*.kmodsfs" ! -path "*/nvidia/*" ! -path "*/rootcopy/*" 2>/dev/null | egrep -ve "firmware|lang|optional" | grep $KERNEL | sort >>/tmp/modules
find $DATADIR/optional -name "*.kmodsfs" 2>/dev/null | egrep -e "$LOAD" | grep $KERNEL | sort >>/tmp/modules

# Find firmware modules
find $DATADEV/$CMDIR/firmware -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >>/tmp/modules

# Detect nvidia video cards on pcie bus
if [ "$NVIDIA" = detect ]; then
	echo "${i}detecting nvidia GPU"
	nvlist=`lspci | grep -i "030.: 10de:" | cut -d":" -f4`
	if [ -n "$nvlist" ]; then
	for nv in $nvlist
	do
		echo "${i}$nv chip found, checking which nvidia driver supports it"
		if grep -sqi 10de$nv /usr/share/nvidia/nvidia.ids; then NVIDIA=nvidia; break
		elif grep -sqi 10de$nv /usr/share/nvidia/nvopen.ids; then NVIDIA=nvopen; break
		elif grep -sqi 10de$nv /usr/share/nvidia/nvidia-tesla-470.ids; then NVIDIA=nv470; break
		elif grep -sqi 10de$nv /usr/share/nvidia/nvidia-legacy-390xx.ids; then NVIDIA=nv390; break
		elif grep -sqi 10de$nv /usr/share/nvidia/nvidia-legacy-340xx.ids; then NVIDIA=nv340; break
		else echo "${i}$nv chip is not supported by nvidia driver"
		fi
	done
	else echo "${i}could not find any nVidia GPU on this PC"
	fi
fi

# Find nvidia modules
if [ "$NVIDIA" ] && [ "$NVIDIA" != detect ]; then
	echo "${i}$NVIDIA NVIDIA driver will be activated"
	find $DATADIR/nvidia -name "$NVIDIA*.kmodsfs" 2>/dev/null | grep $KERNEL >>/tmp/modules
	find $DATADIR/nvidia -name "$NVIDIA*.squashfs" 2>/dev/null | grep -v gsp | egrep -ve "$NOLOAD" >>/tmp/modules
	[ "$NVIDIA" = nvopen ] && find $DATADIR/nvidia -name "nvidia*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" >>/tmp/modules
	NOLOAD="$NOLOAD|mesa-vulkan-drivers"
fi

# Find lang modules
[ "$LANGM" ] && find $DATADEV/$CMDIR/lang -name "*.squashfs" 2>/dev/null | grep -i $LANGM >>/tmp/modules

# Find modules and optional modules
find $DATADIR/modules -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >>/tmp/modules
find $DATADIR/optional -name "*.squashfs" 2>/dev/null | egrep -e "$LOAD" | sort >>/tmp/modules

# Find /llive/modules or /llive/modules32
if [ `uname -m` = i686 ]; then search -d /llive/modules32 && LIVEMOD=modules32
	echo "${i}searching for additional modules in /llive/modules32"
elif [ "$FOLDER" != llive ]; then search -d /llive/modules && LIVEMOD=modules
	echo "${i}searching for additional modules in /llive/modules"
fi
if [ "$LIVEMOD" ]; then
	find /mnt/$DEV/llive/$LIVEMOD -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >>/tmp/modules
	find /mnt/$DEV/llive/$LIVEMOD -name "*.kmodsfs" 2>/dev/null | egrep -ve "$NOLOAD" | grep $KERNEL | sort >>/tmp/modules
fi

# Find extra modules
if [ "$EXTRAMOD" ]; then
for EXTFOLDER in $EXTRAMOD; do
	echo "${i}searching for additional modules in $EXTFOLDER"
	if locate -d "$EXTFOLDER"; then
	find /mnt/$DEV/$LPTH -name "*.squashfs" 2>/dev/null | egrep -ve "$NOLOAD" | sort >>/tmp/modules
#	find /mnt/$DEV/$LPTH -name "*.kmodsfs" 2>/dev/null | egrep -ve "$NOLOAD" | grep $KERNEL | sort >>/tmp/modules
	else echo "${i}couldn't find${BOLD} $EXTFOLDER ${RST}Correct your extramod= cheatcode"
	fi
done
fi

# Copy modules to RAM
param copy2ram && TORAM=1
param toram && TORAM=1
if [ $TORAM ]; then
    MODFILE=/tmp/modules # list of modules
    [ "$RAMMOD" ] && { egrep -e "$RAMMOD" /tmp/modules > /tmp/rammod; MODFILE=/tmp/rammod; }
    echo "${i}copying data to RAM, this may take some time..."
    NUM=`grep -c '.' $MODFILE`
    while read MODULE; do
        echo -en "${YELLOW}  ($NUM modules left)  ${RST} \r"
        let NUM=NUM-1
        NAME="$(basename "$MODULE")"
        cp "$MODULE" /memory/copy2ram 2>/dev/null
        [ $? -eq 0 ] && { sed -i "s@^.*/$NAME@/memory/copy2ram/$NAME@" /tmp/modules; continue; }
        rm /memory/copy2ram/"$NAME"
        echo "${i}${CYAN}Cannot copy $NAME Other modules will be skipped${RST}"
        #find /memory/copy2ram -name "*.kmodsfs" | sort >/tmp/modules
        #find /memory/copy2ram -name "*.squashfs" | sort >>/tmp/modules
        break
    done < $MODFILE
    echo -en "                       \r"
fi

# Mount modules
NUM=0
echo "/memory/images/01-filesystem.squashfs" >/tmp/lowerdir
MODULE="`grep -m1 '/01-filesystem.squashfs$' /tmp/modules`"
if [ -n "$MODULE" ]; then
	NAME="01-filesystem.squashfs"
	mount_module # mount 01-filesystem.squashfs if existed
else
	mkdir -p /memory/images/"01-filesystem.squashfs"
fi

# Mount .kmodsfs kernel modules squashfs
grep '.kmodsfs$' /tmp/modules | while read MODULE; do
NAME="$(basename "${MODULE%.*}")" # remove extension .kmodsfs
mount_module
done

# Mount other modules from list /tmp/modules
grep -v '/01-filesystem.squashfs$' /tmp/modules | grep -v '.kmodsfs$' | while read MODULE; do
NAME="$(basename "${MODULE%.*}" | tr -d ' ')" # remove extension .squashfs
NAME="${NAME:0:14}" # truncate mountpoint name
mount_module
done

[ "$PFULL" ] && UDIR=filesystem || UDIR=upperdir
UPPERDIR=/memory/changes/$UDIR
WORKDIR=/memory/changes/workdir

[ "$CHANGES" = memory ] || clean_changes_dir
mkdir -p $UPPERDIR/mnt/live $WORKDIR
if [ -d /memory/images/changes-exit ]; then
	clean_changes_dir /memory/images/changes-exit
	mkdir -p /memory/images/changes-exit/$UDIR/mnt/live
	mkdir -p /memory/images/changes-exit/workdir
	echo "/memory/images/changes-exit/$UDIR" >>/tmp/lowerdir
	cp -a /memory/images/changes-exit/workdir/* $WORKDIR/. 2> /dev/null
fi

# Setup lowerdir list
LOWLIST="`cat /tmp/lowerdir | tac`"
LOWLIST="`echo $LOWLIST | sed 's/ /:/g'`"

# Mount overlayfs
mount -t overlay -o upperdir=$UPPERDIR,lowerdir=$LOWLIST,workdir=$WORKDIR overlay /union
if [ $? -ne 0 ]; then
	echo "${RED}ERROR Something went wrong. Press Ctrl+Alt+Del to reboot.${RST}"
	sh
fi

debug

# Copy /rootcopy folder
if param norootcopy ; then
	ROOTCOPY=none
	echo "${i}skipping /rootcopy directory"
elif [ $ROOTCOPY ] && locate -d $ROOTCOPY ; then
	echo "${i}copying content of $ROOTCOPY directory"
	cp -af /mnt/$DEV/$LPTH/. /union/. 2>/dev/null
elif [ $ROOTCOPY ]; then
	echo "${i}couldn't find${BOLD} $ROOTCOPY ${RST}Correct your rootcopy= cheatcode"
	ROOTCOPY=none
elif search -d /llive/rootcopy ; then
	ROOTCOPY=/llive/rootcopy
	echo "${i}copying content of /mnt/$DEV/llive/rootcopy directory"
	cp -af /mnt/$DEV/llive/rootcopy/. /union/. 2>/dev/null
else
	ROOTCOPY=none
	echo "${i}copying content of $DATADIR/rootcopy directory"
	cp -af $DATADIR/rootcopy/. /union/. 2>/dev/null
fi

# Copy /etc/resolv.conf
if [ $IP ] && [ -f /etc/resolv.conf ]; then
	[ -L /union/etc/resolv.conf ] && rm -f /union/etc/resolv.conf
	cat /etc/resolv.conf >> /union/etc/resolv.conf
fi

# Unload unused ata_ kernel modules
for MODULE in `sed 's/ /\n/g' modlist | grep ata_ ; echo pata_sis`
do rmmod $MODULE 2>/dev/null
done

# Unload unused mmc kernel modules
for MODULE in $MODLISTMMC cb710 tifm_core sdhci cqhci mmc_core
do rmmod $MODULE 2>/dev/null
done

debug

# Remove /union/mnt/XX dir's
for x in `ls -1 /union/mnt | grep -v live`; do
	[ -d /union/mnt/$x ] && rmdir /union/mnt/$x # Will fail if dir not empty!
	[ -L /union/mnt/$x ] && rm -f /union/mnt/$x
done

# Create /mnt/home symlink
if [ "$BOOTDEV" ] && [ -d "$BOOTDEV" ]; then
ln -snf $BOOTDEV /union/mnt/home
elif [ -d "$DATADEV" ]; then
ln -snf $DATADEV /union/mnt/home
fi

# Create /mnt/saved symlink
if [ -d /memory/images/changes-exit ]; then
ln -snf /mnt/live/memory/images/changes-exit /union/mnt/saved
else
ln -snf /mnt/live/memory/changes /union/mnt/saved
fi

MNTPOINTS=`grep /mnt/ /etc/fstab | cut -d" " -f2`
[ -d /mnt/nfs ] && MNTPOINTS="/mnt/nfs $MNTPOINTS"
[ -d /mnt/nfsrw ] && MNTPOINTS="/mnt/nfsrw $MNTPOINTS"
[ -d /mnt/isoloop ] && MNTPOINTS="/mnt/isoloop $MNTPOINTS"
if [ "$CHNDEV" != memory ] && [ -d "$CHNDEV" ]; then
MNTPOINTS="$CHNDEV $MNTPOINTS"
fi

# Unmount or remount,rw and move mountpoints /mnt/XX to /union/mnt/XX
for MNTDEV in $MNTPOINTS
do mkdir -p /union"$MNTDEV"
if [ "$MNTDEV" = "$CHNDEV" ]; then # keep CHNDEV mounted
    mount -o move "$MNTDEV" /union"$MNTDEV" 2>/dev/null
elif [ "$MNTDEV" = "$DATADEV" -o "$MNTDEV" = "$BOOTDEV" ]; then
    if [ $TORAM ] && [ "$MOUNT" = ro -o "$MOUNT" = noauto ]; then
        umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
    elif [ "$MNTDEV" = /mnt/isoloop -o "$MNTDEV" = /mnt/nfs ]; then
        mount -o move "$MNTDEV" /union"$MNTDEV"
    elif [ "$MOUNT" = ro ]; then # try remount,rw if copy2ram not used
        mount -o remount,rw "$MNTDEV" 2>/dev/null
        mount -o move "$MNTDEV" /union"$MNTDEV"
    else
        mount -o move "$MNTDEV" /union"$MNTDEV"
    fi
elif [ "$MOUNT" = ro ]; then # try remount,rw if filesystem in use
    umount "$MNTDEV" 2>/dev/null || { mount -o remount,rw "$MNTDEV" 2>/dev/null; mount -o move "$MNTDEV" /union"$MNTDEV"; }
elif [ "$MOUNT" = noauto ]; then # try unmount unused mountpoints if noauto
    umount "$MNTDEV" 2>/dev/null || mount -o move "$MNTDEV" /union"$MNTDEV"
else
    mount -o move "$MNTDEV" /union"$MNTDEV" # move all mountpoints if noauto not used
fi
done

# Remove unused /mnt/XX dir's
rmdir /mnt/* 2>/dev/null

if [ $TORAM ] && [ "$MOUNT" = ro ] && [ -z "`grep -v memory/copy2ram /tmp/modules`" ]; then
	echo "${i}${GREEN}finished copying to RAM - booting media can be removed safely${RST}"
fi

debug

# Create debug file:
if [ -e /tmp/devices ]; then
echo "# Recognized devices:" >$livedbg
cat /tmp/devices >>$livedbg
fi
[ $BOOTDEV ] && DATADEV=$BOOTDEV
echo $DATADEV > /etc/cfgdev # used in script 'pseudofull-setup'
echo -e "\n# Booting device:\n$DATADEV
\n# data found in:\n$DATADIR
\n# Changes are stored in:\n$CHANGES
\n# Non standard /rootcopy dir:\n$ROOTCOPY
\n# Modules activated during boot time:" >>$livedbg
cat /tmp/modules >>$livedbg
[ "$ISOSRC" ] && echo -e "\n# ISO=$ISOSRC" >> $livedbg
cp -af $livedbg /union/var/log/

cat /proc/cmdline

echo "${i}changing root directory"
if [ -x /union/usr/sbin/init ]; then
	cp -f /union/usr/sbin/init /bin
	INIT=init
elif [ -x /union/usr/lib/systemd/systemd ]; then
	cp -f /union/usr/lib/systemd/systemd /bin
	INIT=systemd
fi

if [ -x /bin/$INIT ]; then
	cp -af /dev/console /union/dev
	mkdir -p /union/mnt/live
	echo "${BOLD}live system is ready now - starting Debian${RST}"
	pivot_root /union /union/mnt/live
	exec /mnt/live/bin/chroot . /mnt/live/bin/$INIT "$@" <dev/console >dev/console 2>&1
else
	echo "${RED}ERROR Something went wrong. Press Ctrl+Alt+Del to reboot.${RST}"
	sh
fi
