#!/bin/bash

# build script create a Debian minimal live system similar to 'DebianDog'
# supports only .conf files as an argument, e.g. ./build /path/to/myconfig.conf

# Based on https://github.com/DebianDog/build-trixie by fredx181
# Modified by gumanzoy https://github.com/gumanzoy/build-live-iso

if [ -f "$1" ]; then
	config="$1"
	. "$config"
else
	echo "Please run again, e.g. 'sudo ./$(basename $0) <config>'"
	exit
fi

if [ "`whoami`" != "root" ]; then
	echo "This script should be run as root"
	echo "Please run again, e.g. 'sudo ./$(basename $0) <config>'"
	exit
fi

if [ -z "$PL_BASE" ] || [ -z "$INSTALL" ]; then
	echo -e "\e[0;31mThis config file cannot be used, sorry, exiting...\e[0m"
	exit
else
	echo -e "\e[0;36mRunning with configuration:\e[0m $(readlink -f $config)"
fi

export LD_LIBRARY_PATH=
export LAUNCHDIR="$PWD"

export DIST=`basename "$config" | cut -d- -f1`
if [ ! -d "$DIST" ]; then
	echo -e "\e[0;33mDirectory '""$DIST""' not exist, exiting...\e[0m"
	exit
fi

echo -e "\e[0;33mCreate a Debian $DIST minimal live system similar to 'DebianDog'\nWith overlay support and porteus-boot style included\e[0m"
echo -e "\e[0;33m\nIt's required to have at least 3 GB free space\nand to run this script on a Linux filesystem, e.g. ext4\e[0m"
echo -e "\e[0;32mBuilding will be done in:\e[0m $LAUNCHDIR/$DIST"

if [ $(command -v apt-get 2>/dev/null) ]; then
	#echo -e "\e[0;36mUpdate the package lists...\e[0m"
	#apt-get update
	echo -e "\e[0;36mInstall required packages:\e[0m"
	echo "debootstrap squashfs-tools xz-utils zstd grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso"
	apt-get install debootstrap squashfs-tools xz-utils zstd grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso -y
fi

if [ -z `which debootstrap` ] || [ ! -e /usr/share/debootstrap/scripts/"$DIST" ]; then
	echo -e "\e[0;31mFile /usr/share/debootstrap/scripts/$DIST not found, exiting..."
	echo -e "\e[0;36mPlease install required packages:\e[0m"
	echo "debootstrap (>=1.0.134) squashfs-tools xz-utils zstd grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso"
	exit
fi

########### Functions ###########

# This makes sure when the script is interrupted, that all mount 'binds' will unmount
exitfn () {
trap SIGINT              # Resore signal handling for SIGINT
echo -e "\e[0;36mUnmounting mount binds in chroot\e[0m"
umount -l "$LAUNCHDIR/$DIST"/chroot/proc 2> /dev/null
umount -l "$LAUNCHDIR/$DIST"/chroot/sys 2> /dev/null
umount -l "$LAUNCHDIR/$DIST"/chroot/dev/pts 2> /dev/null
umount -l "$LAUNCHDIR/$DIST"/chroot/dev 2> /dev/null

rm -f "$LAUNCHDIR/$DIST"/apt/archives/lock 2> /dev/null

if mountpoint -q "$LAUNCHDIR/$DIST"/chroot/dev; then     # just in case check dev
	echo -e "\e[0;31mSomething went wrong, directory chroot cannot be removed\e[0m"
	echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\e[0m"
	exit
else
	rm -f "$LAUNCHDIR/$DIST"/*.conf 2> /dev/null
fi
exit
}
export -f exitfn

trap "exitfn" 1 2 3 15    # Set up SIGINT trap to call function 'exitfn'

# OK or FAILED
ok_or_failed () {
[ $? -eq 0 ] && echo -e "\e[0;32mOK\e[0m" || echo -e "\e[0;31mFAILED\e[0m"
}
export -f ok_or_failed

ok_or_failed_chroot () {
[ $? -eq 0 ] && echo -e "\e[0;32mOK\e[0m" && return 0
echo -e "\e[0;31mFAILED\e[0m"
touch /exit_
exit
}
export -f ok_or_failed_chroot

apt_get () {
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $@
# try again if failed
if [ $? -ne 0 ]; then
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $@
ok_or_failed_chroot
fi
}
export -f apt_get

########### Options (configuration)  ###########

if [ "$(uname -m)" = "i686" ]; then
	echo -e "\e[0;32mOK, running 32-bit OS, building live system for 32-bit: $(uname -m)\e[0m"
	export ARCH="i386"
elif [ "$(uname -m)" = "x86_64" ]; then
	if [ "$BUILD686" = "TRUE" ]; then
		echo -e "\e[0;32mOK, running 64-bit OS, building live system for 32-bit: i686\e[0m"
		export ARCH="i386"
	else
		echo -e "\e[0;32mOK, running 64-bit OS, building live system for 64-bit: $(uname -m)\e[0m"
		export ARCH="amd64"
	fi
fi

if [ -n "$DE_CONFIG" ]; then
	export DE_CONFIG="$DE_CONFIG"
else
	export DE_CONFIG=`basename "$config" .conf | cut -d- -f2`
fi
export DECONFDIR="$DE_CONFIG"'conf'
if [ ! -d "$DIST/$DECONFDIR" ]; then
	echo -e "\e[0;33mDirectory '""$DIST/$DECONFDIR""' not exist, exiting...\e[0m"
	exit
fi

[ -z "$GUESTUSER" ] && GUESTUSER=guest
export GUESTUSER="$GUESTUSER"
[ -n "$GUESTPASS" ] && export GUESTPASS="$GUESTPASS"
[ -n "$LOGINUSER" ] && export LOGINUSER="$LOGINUSER"

[ -z "$LKERNEL" ] && LKERNEL=current
export LKERNEL="$LKERNEL"

if [ "$BUILDFW" = "TRUE" ]; then
	if [ -n "`ls $DIST/isodata/live/firmware/fw-*.squashfs 2> /dev/null`" ]; then
		echo -e "\e[0;32mOK, $DIST/isodata/live/firmware is not empty - skip creating firmware modules\e[0m"
		export BUILDFW=FALSE
	else
		echo -e "\e[0;33mBUILDFW=TRUE - live/firmware/fw-*.squashfs modules will be created\e[0m"
		export BUILDFW=TRUE
	fi
else
	echo -e "\e[0;33mBUILDFW=FALSE - skip creating firmware modules\e[0m"
	export BUILDFW=FALSE
fi

if [ -n "$TEMPMIRROR" ]; then
	MIRRORURL="http://""$TEMPMIRROR""/debian/"
else
	MIRRORURL="http://deb.debian.org/debian/"
fi

# Export final variables defined from custom .conf file
export SYSTEMD="$SYSTEMD"
export PL_BASE="$PL_BASE"
export PL_SYSV="$PL_SYSV"
export PL_SYSTEMD="$PL_SYSTEMD"

# Merge INSTALL= and PL_AMD64= variables into one
[ "$ARCH" = "amd64" ] && INSTALL="$INSTALL $PL_AMD64"
export INSTALL="$INSTALL"

########## Set up debootstrap ##########
echo -e "\e[0;36mSetting up debootstrap in $DIST/chroot, this will take a few minutes\e[0m"

if [ -d "$DIST/chroot" ]; then
	echo -e "\e[0;36mUnmount mount binds and remove $DIST/chroot...\e[0m"
	umount -l $DIST/chroot/proc 2> /dev/null
	umount -l $DIST/chroot/sys 2> /dev/null
	umount -l $DIST/chroot/dev/pts 2> /dev/null
	umount -l $DIST/chroot/dev 2> /dev/null

	mv $DIST/chroot/var/cache/apt $DIST/ 2> /dev/null
	if mountpoint -q $DIST/chroot/dev; then      # just in case check dev
		echo -e "\e[0;31mSomething went wrong, directory $DIST/chroot cannot be removed\e[0m"
		echo -e "\e[0;31mMake sure it's not in use by some process and try again, exiting...\e[0m"
		exit
	else
		rm -rf $DIST/chroot
	fi
	mkdir -p $DIST/chroot/var/cache
	mv $DIST/apt $DIST/chroot/var/cache/ 2> /dev/null
	echo -e "\e[0;32mOK, continue...\e[0m"
else
	mkdir -p $DIST/chroot
fi

# Copy config co chroot/root
mkdir -p $DIST/chroot/root
grep -v ^GUESTPASS "$config" > $DIST/chroot/root/`basename "$config"`

# Run debootstrap
cd $DIST && debootstrap --arch=$ARCH --variant=minbase \
--include=apt-transport-https,ca-certificates,adduser "$DIST" chroot "$MIRRORURL"
ret=$?
echo $ret
if [ $ret -ne 0 ]; then
	echo -e "\e[0;31mFailed to install the base system\e[0m"
	echo -e "\e[0;32mThis can happen sometimes, please try again, exiting now...\e[0m"
	exit
fi

# Cleaning after debootstrap
rm -rf chroot/usr/share/doc/*/examples
find chroot/usr/share/doc -type f ! -name copyright -delete 2> /dev/null
rm -rf chroot/usr/share/info/*

if [ -z "$KEEPLOCALES" ]; then
	rm -rf chroot/usr/share/locale/??
	rm -rf chroot/usr/share/locale/??_*
	rm -rf chroot/usr/share/locale/??@*
	rm -rf chroot/usr/share/locale/???
	rm -rf chroot/usr/share/man/??
	rm -rf chroot/usr/share/man/??.*
	rm -rf chroot/usr/share/man/*_*
else
GREPLOCALES="`echo "$KEEPLOCALES" | sed 's/ /|/g'`"
ls chroot/usr/share/locale | grep -v locale.alias | egrep -ve "$GREPLOCALES" | while read DIR
do rm -rf chroot/usr/share/locale/"$DIR"
done
ls chroot/usr/share/man | grep -v man | egrep -ve "$GREPLOCALES" | while read DIR
do rm -rf chroot/usr/share/man/"$DIR"
done
fi

# Remove debootstrap sources.list. Will use deb822 style /etc/apt/sources.list.d/debian.sources instead
rm chroot/etc/apt/sources.list

cp --preserve=mode,timestamps -rf rootcopy/* chroot/
ok_or_failed

mkdir chroot/de_conf
cp --preserve=mode,timestamps -rf "$DECONFDIR"/* chroot/de_conf/
ok_or_failed

if [ -n "$TEMPMIRROR" ]; then
	sed -i s/deb.debian.org/"$TEMPMIRROR"/ chroot/etc/apt/sources.list.d/debian.sources
fi

[ -n "$XKBLAYOUT" ] || XKBLAYOUT="us"
echo "XKBLAYOUT=\"$XKBLAYOUT\"" >> chroot/etc/default/keyboard
echo "XKBVARIANT=\"$XKBVARIANT\"" >> chroot/etc/default/keyboard

if [ -n "$KEEPLOCALES" ]; then
for KEEPLOCALE in $KEEPLOCALES
do
	echo "path-include=/usr/share/locale/$KEEPLOCALE/*" >> chroot/etc/dpkg/dpkg.cfg.d/usr_share_locale_man
	echo "path-include=/usr/share/man/$KEEPLOCALE/*" >> chroot/etc/dpkg/dpkg.cfg.d/usr_share_locale_man
done
fi

if [ -n "$KEEPLOCALES" ]; then
echo "$KEEPLOCALES" | grep -q cs && sed -i 's/# cs_CZ.UTF-8/cs_CZ.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q hu && sed -i 's/# hu_HU.UTF-8/hu_HU.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q nb && sed -i 's/# nb_NO.UTF-8/nb_NO.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q nl && sed -i 's/# nl_NL.UTF-8/nl_NL.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q pl && sed -i 's/# pl_PL.UTF-8/pl_PL.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q ro && sed -i 's/# ro_RO.UTF-8/ro_RO.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q sv && sed -i 's/# sv_SE.UTF-8/sv_SE.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q tr && sed -i 's/# tr_TR.UTF-8/tr_TR.UTF-8/' chroot/etc/locale.gen
echo "$KEEPLOCALES" | grep -q uk && sed -i 's/# uk_UA.UTF-8/uk_UA.UTF-8/' chroot/etc/locale.gen
fi

# mount bind some required directories from host filesystem
mount --bind /proc chroot/proc
mount --bind /dev chroot/dev
mount --bind /sys chroot/sys
mount -t devpts devpts chroot/dev/pts
# provide a network connection in chroot
echo -en "`cat /etc/resolv.conf`" > chroot/etc/resolv.conf

#################################################
############ Start running in chroot ############
#################################################
chroot_in () {

export HOME=/root
export LC_ALL=C

# Setup install without install recommends
echo "APT::Install-Recommends "false"; APT::Install-Suggests "false";" > /etc/apt/apt.conf
echo "Acquire::Check-Valid-Until "0";" >> /etc/apt/apt.conf

if [ "$SYSTEMD" = "FALSE" ]; then
	PL_SYS="$PL_SYSV"
elif [ "$SYSTEMD" = "TRUE" ]; then
	rm -f /etc/apt/preferences.d/00systemd /etc/apt/preferences.d/devuan
	rm -f /etc/apt/sources.list.d/devuan.sources /usr/share/keyrings/devuan-archive-keyring.gpg
	PL_SYS="$PL_SYSTEMD"
fi

# Add architecture i386 (in case of some :i386 packages listed in INSTALL=)
if echo "$INSTALL" | grep -q ':i386'
then dpkg --add-architecture i386
fi

apt-get update # required, repositories just added
[ $? -ne 0 ] && apt-get update # try again if failed

# Create GUESTUSER non-root user
adduser "$GUESTUSER" --gecos ",,," --disabled-password 2> /dev/null
if [ -n "$GUESTPASS" ]; then
	echo -e "$GUESTPASS\n$GUESTPASS" | passwd "$GUESTUSER" 2> /dev/null
	usermod -a -G sudo,cdrom,audio,video,plugdev "$GUESTUSER"
else
	usermod -a -G cdrom,audio,video,plugdev "$GUESTUSER"
fi

############ Start installing packages ############
echo -e "\e[0;36mInstall sysvinit/systemd required packages\e[0m"
apt_get install $PL_SYS

# Run 'apt-get upgrade' to force update packages from security.debian.org
apt_get upgrade

# Install some basic packages
apt_get install $PL_BASE

dbus-uuidgen > /var/lib/dbus/machine-id
echo "live" > /etc/hostname
echo "127.0.0.1	 localhost" > /etc/hosts
echo "127.0.1.1	 live" >> /etc/hosts
mkdir -p /opt/bin

# For Trixie install sqv-dummy and purge sqv
if [ "$DIST" = "trixie" ]; then
apt-get install --yes sqv-dummy && apt-get purge --yes sqv
fi

# Simulate install first to check for errors, if there are, exit
echo -e "\e[0;36mChecking packages . . .\e[0m"
apt-get install -s -y $INSTALL
ret=$?
if [ $ret -eq 100 ]; then
	echo -e "\e[0;31mSorry, there are one or more errors, see above.\e[0m"
	echo -e "\e[0;31mCould be a typo in a package name.\e[0m"
	echo -e "\e[0;36mExiting . . .\e[0m"
	touch /exit_
	exit
else
	echo -e "\e[0;32mAll packages checked OK, continue now to install packages...\e[0m"
fi

### Do the real installing
apt_get install $INSTALL

# Download linux-image package, create initrd1.xz and kernel.kmodsfs module
echo -e "\e[0;36mCreate initrd1.xz and .kmodsfs module\e[0m"
/usr/local/sbin/mkkernsfs "$LKERNEL"
ok_or_failed_chroot

# Download firmware packages and create fw-*.squashfs modules
if [ "$BUILDFW" = "TRUE" ]; then
	echo -e "\e[0;36mDownload firmware packages and create fw-*.squashfs modules\e[0m"
	/usr/local/sbin/mkfwsfs create
fi

# Uninstall gnome-icon-theme (check for reverse dependencies, remove only if none)
GNOME_ICON=$(apt-cache rdepends --installed gnome-icon-theme | grep -v "gnome-icon-theme\|Reverse Depends" | grep -v "|")
[ -z "$GNOME_ICON" ] && apt-get purge --yes gnome-icon-theme    # in case installed

### apt-get autoremove
apt-get --yes autoremove

############ End of installing packages ############

# Use functions uncompress_files and remove_broken_links from linux-live
# https://github.com/Tomas-M/linux-live/blob/master/Slax/debian12/cleanup

# Unzip gzipped files (man pages), so LZMA can compress 2times better.
# First we fix symlinks, then uncompress files
# $1 = search directory
uncompress_files() {
local LINK LINE

find "$1" -type l -name "*.gz" | while read LINE; do
	LINK="$(readlink "$LINE" | sed -r 's/.gz$//')"
	FILE="$(echo "$LINE" | sed -r 's/.gz$//')"
	ln -sfn "$LINK" "$FILE"
	rm -f "$LINE"
done
find "$1" -type f -name "*.gz" | xargs -r gunzip -f
}

uncompress_files etc/alternatives
uncompress_files usr/share/man

# remove broken links
# $1 = search directory
remove_broken_links() {
find "$1" -xtype l -delete 2> /dev/null
}

remove_broken_links etc/alternatives
remove_broken_links usr/share/man

# Re-create man-db /var/cache/man/
mandb --create

# Enable traditional network interface names for systemd
mkdir -p /etc/systemd/network
ln -sf /dev/null /etc/systemd/network/99-default.link

if [ "$SYSTEMD" = "FALSE" ]; then
# Enable /etc/init.d/snapexit (Save on exit when shutdown from console)
	update-rc.d snapexit defaults
# Disable unneeded initscripts
#	sed -i s/'# Required-Start:    checkroot'/'# Required-Start:'/ etc/init.d/checkroot-bootclean.sh
	update-rc.d mountall-bootclean.sh disable 2> /dev/null
	update-rc.d mountall.sh disable 2> /dev/null
	update-rc.d checkfs.sh disable 2> /dev/null
	update-rc.d checkroot-bootclean.sh disable 2> /dev/null
	update-rc.d checkroot.sh disable 2> /dev/null
# Enable pin priority 99 to initscripts package to disable auto updating
	sed -i s/init-scripts/initscripts/g /etc/apt/preferences.d/noupgrades
# Disable alsactl warning messages
	sed -i s/'log_action_cont_msg'/'#log_action_cont_msg'/g /etc/init.d/alsa-utils 2> /dev/null
fi

if [ -s /etc/X11/default-display-manager ]; then
# Disable tty1 autologin, using display-manager
	echo -en "\e[0;32mDisable tty1 autologin, using display-manager: \e[0m"
	cat /etc/X11/default-display-manager
	rm -f /etc/systemd/system/graphical.target.wants/getty@tty1.service
	rm -f /etc/systemd/system/getty.target.wants/getty@tty1.service
elif [ -n "$LOGINUSER" ]; then
# Enable tty1 auto login for non-root user
	echo -e "\e[0;32mEnable autologin for $LOGINUSER user\e[0m"
	[ "$SYSTEMD" = "FALSE" ] && sed -i "s/getty --noclear/getty --noclear -a $LOGINUSER/" /etc/inittab
	sed -i "s/--noclear -a root/--noclear -a $LOGINUSER/" /etc/systemd/system/getty@tty1.service
elif [ "$SYSTEMD" = "FALSE" ]; then
# Enable tty1 auto login for root
	sed -i "s/getty --noclear/getty --noclear -a root/" /etc/inittab
fi

# Create symlink for /usr/local/sbin/mount.ntfs
ln -sf /usr/local/sbin/mount.ntfs /usr/sbin/mount.ntfs

# Enable pin priority 99 to ntfs-3g package to disable auto updating
sed -i s/ntfs3g/ntfs-3g/g /etc/apt/preferences.d/noupgrades

# Copy de_conf/ to /
cp --preserve=mode,timestamps -rf de_conf/* ./
rm -rf de_conf

# After replacing org.gtk.Settings.FileChooser.gschema.xml with modified version
# Need update /usr/share/glib-2.0/schemas/gschemas.compiled file
if [ "$ARCH" = "amd64" ]; then
/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas /usr/share/glib-2.0/schemas/
elif [ "$ARCH" = "i386" ]; then
/usr/lib/i386-linux-gnu/glib-2.0/glib-compile-schemas /usr/share/glib-2.0/schemas/
fi

mkdir -p root/{Desktop,Startup,.config} home/"$GUESTUSER"/{Desktop,Downloads,Startup,.config}
ln -s /home/"$GUESTUSER"/Downloads /root/Downloads

# Copy /etc/skel/.config to /root/ and /home/guest/
cp --preserve=mode,timestamps -rf etc/skel/.config/* root/.config/ 2> /dev/null
cp --preserve=mode,timestamps -rf etc/skel/.config/* home/"$GUESTUSER"/.config/ 2> /dev/null

# Copy /etc/skel/Startup to /root/ and /home/guest/
cp --preserve=mode,timestamps -df etc/skel/Startup/* root/Startup/ 2> /dev/null
cp --preserve=mode,timestamps -df etc/skel/Startup/* home/"$GUESTUSER"/Startup/ 2> /dev/null

# chown /home/guest
chown -R "$GUESTUSER":"$GUESTUSER" home/"$GUESTUSER"

# Create symlinks for devices icons
if [ -d usr/share/icons/devices ]; then
for SIZE in 16x16 22x22 24x24 32x32 48x48; do
	cp -df usr/share/icons/devices/* usr/share/icons/AdwaitaLegacy/$SIZE/devices/ 2> /dev/null
done
rm -rf usr/share/icons/devices
fi

remove_broken_links usr/share/icons/Adwaita
remove_broken_links usr/share/icons/AdwaitaLegacy
remove_broken_links usr/share/icons/Numix
remove_broken_links usr/share/icons/Numix-Light

# Remove empty dir's
rmdir usr/share/icons/Adwaita/*/* 2> /dev/null
rmdir usr/share/icons/Adwaita/* 2> /dev/null
rmdir usr/share/icons/AdwaitaLegacy/*/* 2> /dev/null
rmdir usr/share/icons/Numix/*/* 2> /dev/null
rmdir usr/share/icons/Numix-Light/*/* 2> /dev/null
rmdir usr/share/icons/Numix-Light/* 2> /dev/null
remove_broken_links usr/share/icons/Numix-Light
rmdir usr/share/icons/Numix-Light 2> /dev/null

rmdir usr/share/locale/*/* 2> /dev/null
rmdir usr/share/locale/* 2> /dev/null

# Update /usr/share/icons/hicolor/index.theme
update-icon-caches usr/share/icons/*/

# Update /usr/share/applications/mimeinfo.cache
# It is need to do after change .desktop files
update-desktop-database

# Replace symlink for mesa-amber i915_dri.so -> i830_dri.so
[ -f usr/lib/x86_64-linux-gnu/dri/i830_dri.so ] && ln -sf i830_dri.so usr/lib/x86_64-linux-gnu/dri/i915_dri.so
[ -f usr/lib/i386-linux-gnu/dri/i830_dri.so ] && ln -sf i830_dri.so usr/lib/i386-linux-gnu/dri/i915_dri.so

# Enable /etc/fonts/conf.d/10-hinting-full.conf
[ -f etc/fonts/conf.d/10-hinting-full.conf ] && rm -f etc/fonts/conf.d/10-hinting-slight.conf

echo "Cleaning..."
rm -f var/cache/apt/*.bin
rm -f var/cache/debconf/*-old

find var/lib/apt/lists -type f ! -name lock -delete 2> /dev/null

rm -f var/lib/alsa/asound.state
rm -f var/lib/dhcp/*.leases
rm -f var/lib/dhcpcd/*.lease
rm -f var/lib/dpkg/*-old
rm -f var/log/apt/*
rm -f var/log/{alternatives.log,bootstrap.log,dpkg.log}

rm -rf usr/share/doc/*/examples

rm -f var/lib/dbus/machine-id
rm etc/resolv.conf
touch etc/resolv.conf
}
export -f chroot_in

if [ "$(which chroot)" = "/bin/chroot" ]; then
CHROOT="/usr/sbin/chroot"
else
CHROOT="chroot"
fi

$CHROOT chroot /bin/bash -c chroot_in

# do not continue if there were errors
[ -f "chroot/exit_" ] && exitfn

################################################
############ End running in chroot #############
################################################

echo -e "\e[0;36mUnmounting mount binds in chroot\e[0m"
umount -l chroot/proc
umount -l chroot/dev/pts
umount -l chroot/dev
umount -l chroot/sys

cd "$LAUNCHDIR/$DIST/"

# Copy /etc/skel/{.bashrc,.profile} to /root/
cp chroot/etc/skel/{.bashrc,.profile} chroot/root/

# Create compatibility symlink /etc/mtab
ln -sf /proc/self/mounts chroot/etc/mtab

if [ -n "$TEMPMIRROR" ]; then
	sed -i s/"$TEMPMIRROR"/deb.debian.org/ chroot/etc/apt/sources.list.d/debian.sources
fi

if [ -n "$LOCALE" ]; then
	echo "LANG=$LOCALE" > chroot/etc/locale.conf
fi

# Move apt cache away from chroot
mkdir -p apt/archives
mv -f chroot/var/cache/apt/archives/*.deb ./apt/archives/

rm -f isodata/live/*.kmodsfs isodata/live/01-filesystem.squashfs # just in case it exists remove first

mkdir -p isodata/live/{firmware,modules,optional}

# Move kernel.kmodsfs initrd1.xz and vmlinuz1 to isodata/live/
mv -f chroot/tmp/linux-image-*/* isodata/live/
ok_or_failed

if [ "$BUILDFW" = "TRUE" ]; then
	mv -f chroot/tmp/firmware-*/fw-*.squashfs isodata/live/firmware/
fi

rm -rf chroot/tmp/*

# Create isodata/live/01-filesystem.squashfs
echo -e "\e[0;36mCreating isodata/live/01-filesystem.squashfs . . .\e[0m"
mksquashfs chroot isodata/live/01-filesystem.squashfs -b 512k $MKSFSCMP
ok_or_failed

# Move back the cache to chroot
mv -f ./apt/archives/*.deb chroot/var/cache/apt/archives/ 2> /dev/null
rm -rf apt 2> /dev/null

echo -e "\e[0;36mFinally creating ISO...\e[0m"

date=`date -Idate`

ISONAME="DebLive_${DIST}_${DE_CONFIG}_${ARCH}_${date}_vtgrub2.iso"

rm -f "$ISONAME" # just in case it exists remove first

cp -rf rootcopy/boot isodata/
ok_or_failed

sed -i "s/isoname.iso/$ISONAME/" isodata/boot/grub/grub.cfg
sed -i "s/isoname.iso/$ISONAME/" isodata/boot/grub/menu.lst

BUILDISO="#!/bin/sh
# https://github.com/gumanzoy/build-live-iso
# sudo apt-get install -y grub-common grub-pc-bin grub-efi-amd64-bin mtools xorriso
grub-mkrescue --locales= -volid DebLive_${DIST} -o DebLive_${DIST}_${DE_CONFIG}_${ARCH}_vtgrub2.iso ./"

echo "$BUILDISO" > isodata/buildiso && chmod +x isodata/buildiso

grub-mkrescue --locales= -volid DebLive_${DIST} -o "$ISONAME" isodata
ok_or_failed

echo -e "\e[0;32mFinished! If all went well, $DIST/$ISONAME has been created."
echo -e "Also the required files for a frugal install are in $DIST/isodata/live folder \n\nHave a good day!\e[0m"

exit 0
