#!/bin/dash

# Run chown -R /home/user
# in case of directory owner user:group do not match

[ -n "`ls -d /home/*/.profile 2> /dev/null`" ] || exit 0

dirname `ls -d /home/*/.profile 2> /dev/null` | while read LINE; do
	GUESTUSER=`basename "$LINE"`
	grep -sq "$GUESTUSER" /etc/group || continue
	STATGUEST=$(stat -c "%U %G" "$LINE")
	[ "$STATGUEST" != "$GUESTUSER $GUESTUSER" ] && chown -R "$GUESTUSER":"$GUESTUSER" "$LINE" 2> /dev/null
done

exit 0
